### ISSUE TITLE
[BUG] Maybe Impossible Levels

### ISSUE THREAD

**Issue by TK846** [EthanSK/Ye-Olde-Meme-Game-2-Public#19]
**Describe the bug**
I was making this level, and first time, when I tried to verify it, I could, by trying to reproduce it while actually playing was impossible and has a extremely different outcome d9d-7dc-4d0

**To Reproduce**
Play the level, fake die in it (touch a red zone) and enter the MTN dew pool and you get launched to the top of the map
![Screenshaot 2023-03-29 175948](https://user-images.githubusercontent.com/123871807/228613954-9980eb19-8d91-498a-80c0-dedfd9f1fd94.png)

**Expected behavior**

I expected the player to launch into the goal, and it did while verifying

**Desktop (please complete the following information):**
Windows 11, Version 0.6

**Additional context**
This could be very bad if people learn to reproduce this and there could be a surge of impossible levels, but the bug is in an example, not a proper game

**Comment by EthanSK** [comment]
yeah, it's not a 100% guarantee, that's the beauty/downfall of a game like this. there will be 'glitches'

at least its a meme game so it can be justified
