### ISSUE TITLE
[BUG] can’t type a level name and description on mobile

### ISSUE THREAD

**Issue by Temnothere** [EthanSK/Ye-Olde-Meme-Game-2-Public#21]
After I made my level, I decided to publish it and then while I was trying to type the level the keyboard didn’t show up. I’m using an iPhone by the way. Can you fix it, please?

Cheers, tem.

**Comment by EthanSK** [comment]
i can't reproduce. Can you show a screenhsot? Are you trying to type on the blue publish page, or did you go to level settings to put the level name?

**Comment by Temnothere** [comment]
I’m trying to type on the blue publish page.

**Comment by Temnothere** [comment]
Turns out i’m stupid
