### ISSUE TITLE
[BUG] Game Crash

### ISSUE THREAD

**Issue by Kuzeysvg** [EthanSK/Ye-Olde-Meme-Game-2-Public#24]
**Describe the bug**
Game crashes when i try to load low rated levels on the selection "All Times"

**To Reproduce**
Click on "Browse Published Levels"
Select the "All Times" selection
Scroll down the levels until the game crashes

**Expected behavior**
The game crashes

*Screenshots**
![IMG_3766](https://github.com/EthanSK/Ye-Olde-Meme-Game-2-Public/assets/73121297/21b9d41c-6fde-403c-922e-3876dd3ad5f9)

**Desktop (please complete the following information):**
 - Operating System: [e.g. MacOS 12.6, Windows 11]

**Additional context**
My phone is an IPhone 8 running on IOS 16.7.7 . And maybe the error could be due to the game's memory allocation limit.

**Comment by EthanSK** [comment]
This should be fixed now. Thanks for reporting. Lmk if it still happpens
